version: 2
jobs:
  build:
    working_directory: ~/fastconcat

    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout
      - restore_cache:
          key: fastconcat-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: fastconcat-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports
